# Generated by Django 3.2.9 on 2021-11-05 21:05

from django.db import migrations
from faker import Faker

fake = Faker()


def gen_data(apps, schema_editor):
    Observatory = apps.get_model("people", "Observatory")
    Observatory.objects.bulk_create(
        [
            gbo := Observatory(name="Green Bank Observatory"),
            nrao := Observatory(name="National Radio Astronomy Observatory"),
        ]
    )

    Site = apps.get_model("people", "Site")
    Site.objects.bulk_create(
        [
            gb_site := Site(observatory=gbo, name="Green Bank"),
            soc_site := Site(observatory=nrao, name="Socorro"),
            cv_site := Site(observatory=nrao, name="Charlottesville"),
        ]
    )

    Person = apps.get_model("people", "Person")
    Person.objects.bulk_create(
        [
            *[Person(name=fake.name(), site=gb_site) for __ in range(10)],
            *[Person(name=fake.name(), site=soc_site) for __ in range(30)],
            *[Person(name=fake.name(), site=cv_site) for __ in range(30)],
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [migrations.RunPython(gen_data)]
